### ISSUE TITLE
No match

### ISSUE THREAD

**Issue by Marcdsv** [paulschuberth/regex-extract-action#103]
I'm trying to extract a part of a markdown file, I tested my regex and it should work, but this action returns nothing.
I have those logs:
```
Run paulschuberth/regex-extract-action@v1.0.1
Inputs
  Haystack: # Test Suites
  - [ ] test
  - [x] ignore
  - [ ] other
  
  # Other info
  - [ ] test
  - [ ] OK
  - [x] nope
  Needle: #+ [T|t]est [S|s]uites\n([\S\s]*)\n\s*\n
  Mode: unique
Outputs
  Matches: 
```
